### ISSUE TITLE
Add a HOWTO explaining how to configure LDAP authentication for APIService users.

### ISSUE THREAD

**Issue by amreo** [ercole-io/ercole-docs#68]
Add a HOWTO explaining how to configure LDAP authentication for APIService users.

This docker image can be used as example: https://github.com/rroemhild/docker-test-openldap

**Comment by amreo** [comment]
A LDAP example can be found here https://github.com/ercole-io/ercole/blob/master/resources/ercole-ldap-example.toml

**Comment by cirelli94** [comment]
Fixed 4142b3f7322ada619b4319bb9634beeb92da397e
