### ISSUE TITLE
HourThreshold should be DaysThreshold

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole-docs#70]
In ercole 2.0 configuration section, it says:
AlertService.FreshnessCheckJob.HourThreshold contains the maximium number of hours in which a hostdata is considered up to date. After this threshold a NO_DATA alert is thrown by the FreshnessCheckJob.

While it should be DaysThreshold and hours --> days

**Comment by amreo** [comment]
Why don't use duration? https://golang.org/pkg/time/#ParseDuration
